Repository googleapis/nodejs-artifact-registry, pull requests merged in 2021-02, with the labels that each got.

#11 chore: update CODEOWNERS config
  .github/CODEOWNERS
  .repo-metadata.json
Labels: automerge, cla: yes

#10 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, cla: yes

#13 chore: update CODEOWNERS, copyright, proto config
  .github/CODEOWNERS
  .jsdoc.js
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  README.md
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1beta2/artifact_registry_client.ts
  src/v1beta2/index.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_artifact_registry_v1beta2.ts
Labels: cla: yes, context: partial

#16 build: fix package name, rerun synthtool
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1beta2/gapic_metadata.json
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
Labels: api: artifactregistry, cla: yes

#17 chore: add resource descriptor style fields
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: artifactregistry, cla: yes, context: none
